name: Java CI with Gradle

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Up container
        run: docker compose up -d
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run Test
        run: ./gradlew test
      - name: upload artifact test content
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test content
          path: build/reports/
